In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# 1 Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.array([1,2,3,4,5])
print(arr)
arr.dtype


In [ ]:
#2  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5,2.6,3,7])
if arr.dtype=='float64':
    print("Yes, that's the data type, float64!")

#Yes, the data type is float 64

In [ ]:
#3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([5j, 6j,7j],dtype=np.complex128)
arr.dtype

In [ ]:
# 4 Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1,2,3,4])
print("The given numpy array is", arr)
print("The original data type is:",arr.dtype)
new_arr= arr.astype(np.float32)
print("The new array is:", new_arr)
print("The data type is:", new_arr.dtype)

In [ ]:
# 5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
float64_arr = np.array([1,2,3,4], dtype= np.float64)
print(float64_arr)
print("The datatype of float64_arr is:",float64_arr.dtype)

new_array = float64_arr.astype(np.float32)
print("The new array of float32 datatype is:",new_array)
print("The datatype of the new_array is:",new_array.dtype)

In [ ]:
# 6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
def array_attributes(arr):
    print("The shape of the array is:",arr.shape)
    print("The size of the array is:",arr.size)
    print("The datatype of the array is:", arr.dtype)

array_attributes(np.array([[1,2,3,4,5],[1,2,3,4,8]]))

In [ ]:
# 7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_attributes(arr):
    return arr.ndim

array_attributes(np.array([[1,2,3,4],[5,6,7,8]]))

In [ ]:

#8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

item_size_info(np.array([[1,2,3,4],[6,8,9,10]]))

In [ ]:
#9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

array_strides(np.array([[[1,2],[3,4],[5,6]]]))

In [ ]:
#10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape
    return arr.strides

shape_stride_relationship(np.array([[1,2],[3,4]]))


In [ ]:
#11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

create_zeros_array(6)

In [ ]:
#12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_one_matrix(rows,cols):
    return np.ones((rows,cols))

create_one_matrix(3,4)

In [ ]:
#13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

generate_range_array(1,10,1)

In [ ]:
#14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

generate_linear_space(1,9,5)


In [ ]:
#15  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

create_identity_matrix(8)


In [ ]:
#16 Write a function that takes a Python list and converts it into a NumPy array.
def conv_to_nparray(list):
    return np.asarray(list)

conv_to_nparray([1,2,3,4,8])

In [ ]:
#17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr_view=arr.view()
arr_view.shape = (10,1)
print("Print of the array",arr)
print("Print of the arr_1",arr_view)

In [ ]:
#18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(array1,array2,axis):
    return np.concatenate((array1,array2),axis)

concatenate_arrays(np.array([1,2]),np.array([3,4]),0)


In [ ]:
#19  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3,4,5])

np.concatenate((arr1,arr2),0)

array([1, 2, 3, 1, 2, 3, 4, 5])

In [ ]:
#20  Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):
    return np.vstack(arrays)

array1 = np.array([1,2,3,4])
array2 = np.array([[4,45,6,7],[12,3,4,6]])
array3 = np.array([5,5,6,7])

vertical_stack([array1,array2,array3])

In [ ]:
#21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range(start,stop,step):
    return np.arange(start,stop+1,step)

create_range(1,10,1) #start as 1, stop as 10, step as 1

In [ ]:
#22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

np.logspace(np.log10(1),np.log10(1000),5)

In [ ]:
#24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
#25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
#26  Access the 3rd element from the given NumPy array.

arr = np.array([10,20,30,40,50])
print("The third element of the numpy array is:",arr[2])

In [ ]:
#27  Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[1,2]

In [ ]:
#28  Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3,8,2,10,5,7])
arr[arr>5]


In [ ]:
#29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

In [ ]:
#30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[:2,1:]

In [ ]:
# 31 .Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.



def extract_elements(array, indices):

    if not isinstance(array, np.ndarray) or not isinstance(indices, np.ndarray):
        raise ValueError("Both input array and indices must be numpy arrays")

    if array.ndim != 2 or indices.ndim != 2:
        raise ValueError("Both input array and indices must be 2D arrays")

    if indices.shape[1] != 2:
        raise ValueError("Indices array must have pairs of indices (shape must be Nx2)")

    return array[indices[:, 0], indices[:, 1]]


array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 0], [2, 2]])

extracted_elements = extract_elements(array, indices)
print(extracted_elements)


In [ ]:

#32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def func_threshold(arr):
    return arr[arr>threshold]

arr = np.array([1,2,3,4,5])
threshold=3

func_threshold(np.array([1,2,3,4,5,6,7,8,9,10]))

In [ ]:
#33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.



In [ ]:
# 34  Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
#35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

arr1 = np.array([

In [ ]:
#36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The new array is\n",arr+5)

In [ ]:
#37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1= np.arange(0,3).reshape((1,3))
arr2 = np.arange(0,3).reshape((3,1))

print("The required arrays are:\n",arr1,"and\n",arr2)


arr1+arr2

In [ ]:
#38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])


arr1_reshaped = arr1[:, :arr2.shape[1]]


result = arr2 + arr1_reshaped


print(result)



[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [ ]:
#39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.



arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print(result)


In [ ]:
#40  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Broadcast arr2 to shape (2, 3) to match arr1's shape
arr2_broadcasted = np.broadcast_to(arr2[:, :2], (2, 3))


result = arr1 * arr2_broadcasted

print(result)


In [ ]:
# 41  Calculate column-wise mean for the given array:

arr = np.array([[1,2,3],[4,5,6]])
print("The columnwise mean for the array is",np.mean(arr,axis=0))

In [ ]:
# 42 Find maximum value in each row of the given array:

arr = np.array([[1,2,3],[4,5,6]])
print("The maximum values in each of the rows:",np.max(arr,axis=1))

In [ ]:
# 43 For the given array, find indices of maximum value in each column.

arr = np.array([[1,2,3],[4,5,6]])
print("The indices of maximum values in each of the columns:",np.argmax(arr,axis=0))

In [ ]:
# 44  For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1,2,3],[4,5,6]])
print("The sum across each row of the array is:",np.sum(arr,axis=1))

In [ ]:
#45 In the given array, check if all elements in each column are even.

arr = np.array([[2,4,6],[3,5,7]])
print("Print true for all the elements that are even:\n",arr%2==0)

In [ ]:
# 46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array =np.array([1,2,3,4,5,6])

def reshape_array(arr):
    m=int(input("Input the number of rows:"))
    n=int(input("Input the number of columns:"))
    if m*n == arr.size:
        return arr.reshape((m,n))

reshape_array(original_array)

In [ ]:
#47 Create a function that takes a matrix as input and returns the flattened array.

input_matrix= np.array([[1,2,3],[4,5,6]])

input_matrix.flatten()

In [ ]:
# 48 Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

def concat(arrays,axis):
    return np.concatenate(arrays,axis=axis) #arrays shows the list of arrays to be conacatenated

concat([array1,array2],axis=0)


In [ ]:
#49  Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

def function_split(arr):

    parts = int(input("In how many parts would you like to divide the array:"))
    axis =  int(input("Along which axis would you like this to happen:"))

    return np.split(arr,parts,axis=axis)

function_split(original_array)

In [ ]:
#50 Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1,2,3,4,5])
indices_to_insert= [2,4]
vales_to_insert=[10,11]


In [ ]:
#51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(1,78,size=(10))
arr2=np.arange(1,11)

print("The first array is",arr1)
print("The second array is",arr2)

print("Element-wise addition of the two arrays is:",arr1+ arr2)

In [ ]:
#52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.


arr1 = np.arange(10, 0, -1)


arr2 = np.arange(1, 11)


result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1,6,size=5)
arr2 = np.arange(1,6)

print("The first array is:",arr1)
print("The second array is:",arr2)

print("Element-wise multiplication of the two yields:",arr1*arr2)

In [ ]:
#54  Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)

print("The first array is:",arr1)
print("The second array is:",arr2)

print("Element-wise division of the two yields:",arr1/arr2)

In [ ]:
#55  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1,6)
arr2 = np.array([5,4,3,2,1])

print("The first array is:",arr1)
print("The second array is:",arr2)

print("Element-wise exponentiation of the two yields:",np.power(arr1,arr2))

In [ ]:
# 56  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello','world','hello','numpy','hello'])

subs = input("Enter the substring whose occurences you would count:")

print("Count of the substrings are:", np.sum(arr== subs))

In [ ]:
# 57 Write a function that extracts uppercase characters from a NumPy array of strings.


arr = np.array(['Hello','World','OpenAI','GPT'])

import numpy as np


uppercase = np.array([char for word in arr for char in word if char.isupper()])

print(uppercase)


['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [ ]:


#58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

arr = np.array(['apple','banana','grape','pineapple'])


a=input("Input the substring you want to replace:")
b=input("Input the substring you want to enter:")

def replace_substring(a,b):
    return np.char.replace(arr,a,b)

replace_substring(a,b)



In [ ]:
#59 Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello','World'])
arr2 = np.array(['Open','AI'])

print("Concatenateion of the two arrays, element-wise is:",np.char.add(arr1,arr2))

In [ ]:
#60 Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


max_length = 0


for word in arr:

    length = len(word)


    if length > max_length:
        max_length = length

print("Length of the longest string:", max_length)


Length of the longest string: 9


In [ ]:





# 61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
import statistics as s

arr = np.random.randint(1,1000,size=100)

print("The mean of the dataset is:",s.mean(arr))
print("The median of the dataset is:",s.median(arr))
print("The mode of the dataset is:",s.mode(arr))
print("The variance of the dataset is:",s.variance(arr))
print("The standard deviation of the dataset is:",s.stdev(arr))


In [ ]:
#62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

arr = np.random.randint(1,100,50)
print("The required array is:",arr)

print("The 25th percentile of the data set:",np.percentile(arr,25))
print("The 75th percentile of the data set:",np.percentile(arr,75))

In [ ]:
# 63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])


correlation = np.corrcoef(arr1,arr2)
print(correlation)

In [ ]:
#64 Create two matrices and perform matrix multiplication using NumPy's `dot` function.

m_1 = np.zeros((5,5))+5
m_2 = np.ones((5,5))

print("The multiplication of the two matrices is:\n",np.dot(m_1,m_2))

In [ ]:
#65  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

arr = np.random.randint(10,1000,size=50)
print("The given array is:",arr)

percentiles = np.percentile(arr,[10,50,90])

print("10th percentile:",percentiles[0])
print("50th percentile:",percentiles[1]) #median of the data
print("90th percentile:",percentiles[2])


In [ ]:
#66 Create a NumPy array of integers and find the index of a specific element.

arr1 = np.arange(1,15)


print("The array is:",arr1)
s=int(input("Enter which element in the array you want to search"))
print("The index of the particular element is:",np.where(arr1==s)[0])

In [ ]:
#67  Generate a random NumPy array and sort it in ascending order.

rand_array = np.random.randint(1,8,size = 10)
print("The given random array is:",rand_array)

sorted_array = np.sort(rand_array)

print("The sorted version of the array is:",sorted_array)


In [ ]:
# 68  Filter elements >20  in the given NumPy array.

arr= np.array([12,25,6,42,8,30])

print("Elements which are greater than 20 in the array:",arr[arr>20])



In [ ]:
# 69 Filter elements which are divisible by 3 from a given NumPy array.

arr= np.array([1,5,8,12,15])

print("The array is:",arr)
print("The elements in the array which are divisible by 3 are:",arr[arr%3==0])

In [ ]:
#70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10,20,30,40,50])
print("The array with the given conditions is:",arr)
print("The filtered array with the given conditions is:", arr[(arr>=20)&(arr<=40)])


In [ ]:
# 71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1,2,3])

print("The byte order of the array is:",arr.dtype.byteorder)

In [ ]:
#72 For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1,2,3],dtype=np.int32)

print("The array after byte swapping is:",arr.byteswap())


In [ ]:
#73 For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1,2,3],dtype = np.int32)

print("The original array is:",arr)
print("The modified array is:",arr.newbyteorder('='))


In [ ]:
#74  For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)


import sys



if sys.byteorder == 'little':

    arr_swapped = arr.byteswap().newbyteorder()
else:

    arr_swapped = arr.byteswap().newbyteorder()

print("Original array:", arr)
print("Byte-swapped array:", arr_swapped)



Original array: [1 2 3]
Byte-swapped array: [1 2 3]


In [ ]:
#75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)



array_byteorder = arr.dtype.byteorder


system_byteorder = sys.byteorder


if (system_byteorder == 'little' and array_byteorder == '>') or (system_byteorder == 'big' and array_byteorder == '<'):
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

print("Array byteorder:", array_byteorder)
print("System byteorder:", system_byteorder)


Byte swapping is not necessary.
Array byteorder: =
System byteorder: little


In [ ]:
#76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1,11)

print("The given array is:",arr1)

copy_arr = arr1

copy_arr[0]=5 #Modifying the first element of the array

print("The final form of the array is:",arr1) #Yes, the modifying the copied array affects the original array


In [ ]:

# 77 Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.eye(5,5)

print("The required matrix is:\n",matrix)
view_slice=matrix[0:3,1:4]
print("The sliced matrix is:\n",view_slice)

view_slice[1,2]=4

view_slice

#Let's see if the matrix got modified

print("The current matrix is:\n",matrix) #Yes! The matrix is modified after the slice was modified


In [ ]:
#78 Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


array_a = np.arange(1, 13).reshape(4, 3)


view_b = array_a[:2, :]


view_b += 5


print("Modified array_a:")
print(array_a)

print("\nSlice view_b:")
print(view_b)

#The original a, therefore, get's altered by the change


Modified array_a:
[[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]

Slice view_b:
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
#79 Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.

orig_array = np.arange(1,9).reshape(2,4)

print("The original array is:\n",orig_array)

reshaped_view = orig_array.reshape(4,2)

print("The reshaped array is:\n",reshaped_view)

reshaped_view[0,1]=67

print("The current version of the original array is:\n",orig_array) #Yes! The original array has changed

In [ ]:
# 80 Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


data = np.random.randint(0, 11, size=(3, 4))

print(data)

data_copy = data[data > 5].copy()  # Use .copy() to ensure it's an independent array

print("\nData copy (elements greater than 5):")
print(data_copy)


data_copy[0] = 99

print("\nModified data_copy:")
print(data_copy)


print("\nOriginal data array after modifying data_copy (should remain unchanged):")
print(data)





[[4 2 6 3]
 [7 0 9 0]
 [4 2 3 7]]

Data copy (elements greater than 5):
[6 7 9 7]

Modified data_copy:
[99  7  9  7]

Original data array after modifying data_copy (should remain unchanged):
[[4 2 6 3]
 [7 0 9 0]
 [4 2 3 7]]


In [ ]:
#81  Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

matrix_1 = np.eye(4,5)
matrix_2 = np.ones((4,5))

print("The first matrix is:\n",matrix_1)
print("The second matrix is:\n",matrix_2)


print("The sum of the two matrices is:\n",matrix_1+matrix_2)
print("The difference of the two matrices is:\n",matrix_1-matrix_2)


In [ ]:
#82 Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

mat1 = np.random.randint(0,5,(3,2))
mat2 = np.random.randint(0,6,(2,4))

print("The matrix multiplication of the two is:\n",mat1@mat2)


In [ ]:
#83 Create a matrix `E` and find its transpose.

mat = np.random.randint(0,10,(3,4))

print("The initial matrix is:\n",mat)
print("The transpose of the matrix is:\n",mat.T)

In [ ]:
#84 Generate a square matrix `F` and compute its determinant.

mat = np.random.randint(0,10,(3,4))

print("The initial matrix is:\n",mat)
print("The transpose of the matrix is:\n",mat.T)


In [ ]:
#85 Create a square matrix `G` and find its inverse.

G = np.random.randint(1,100,(5,5))

print("The required square matrix G is:\n",G)
print("The inverse of the square matrix:\n",np.linalg.inv(G))
